language: node_js
node_js: '12.19.0' # .nvmrc
os: linux

before_script:
  - nvm use
  - npm i
  - npm run parse

script:
  - curl -s -O https://raw.githubusercontent.com/matteobertoldo/ci/deploy.sh
  - chmod u+x deploy.sh
  - ./deploy.sh

notifications:
  email:
    on_success: change
    on_failure: change
