language: node_js
node_js: '12.19.0' # .nvmrc
os: linux

before_script:
  - nvm use
  - npm i
  - npm run parse

install:
  - curl -LO https://github.com/gohugoio/hugo/releases/download/v0.76.5/hugo_0.76.5_Linux-64bit.deb
  - sudo dpkg -i hugo_0.76.5_Linux-64bit.deb

script:
  - npm run build:production

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: public
  on:
    branch: master

git:
  depth: 10

notifications:
  email:
    on_success: change
    on_failure: change
